// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huomzfdfzdjirfybjnud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1b216ZmRmemRqaXJmeWJqbnVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxODMyNzIsImV4cCI6MjA2ODc1OTI3Mn0.0dIyjJpV8hLt5xSCQA3-8o4FL7arfyBvv8PfkduWX18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});